// actions constants

export const IS_LOADING_SIDEBAR = 'IS_LOADING_SIDEBAR';
export const IS_LOADING_DISCUSSION = 'IS_LOADING_DISCUSSION';
export const IS_LOADING_ADD_COMMENT = 'IS_LOADING_ADD_COMMENT';
