// actions constants

export const IS_LOADING_SIDEBAR = 'IS_LOADING_SIDEBAR';
export const IS_LOADING_COMMENTS = 'IS_LOADING_COMMENTS';
export const IS_LOADING_ADD_COMMENT = 'IS_LOADING_ADD_COMMENT';
