// actions constants

export const DONE_LOADING_SIDEBAR = 'DONE_LOADING_SIDEBAR';
export const DONE_LOADING_COMMENTS = 'DONE_LOADING_COMMENTS';
export const DONE_LOADING_ADD_COMMENT = 'DONE_LOADING_ADD_COMMENT';
